IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_ALL_ALERTS_HIST'
AND TABLE_TYPE ='VIEW')
BEGIN
DROP VIEW CEVAC_ALL_ALERTS_HIST
END
GO
CREATE VIEW CEVAC_ALL_ALERTS_HIST AS

WITH original AS(
	SELECT * FROM CEVAC_ALL_ALERTS_HIST_RAW
) SELECT *, dbo.ConvertUTCToLocal(UTCDateTime) AS ETDateTime FROM original