IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_EMERGENCY_DAY'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_POWER_EMERGENCY_DAY
END
GO

CREATE VIEW CEVAC_WATT_POWER_EMERGENCY_DAY
AS

SELECT * FROM CEVAC_WATT_POWER_EMERGENCY_HIST
WHERE UTCDateTime <= GETUTCDATE() AND UTCDateTime >= DATEADD(day, -1, GETUTCDATE())