IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_EMERGENCY_HIST'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_POWER_EMERGENCY_HIST
END
GO

CREATE VIEW CEVAC_WATT_POWER_EMERGENCY_HIST
AS

SELECT 'Building Emergency' AS Alias, UTCDateTime, DATEPART(year, UTCDateTime) AS Year, SUM(ActualValue) AS ActualValue, DATEPART(month, UTCDateTime) AS Month, DATEPART(day, UTCDateTime) AS Day
FROM CEVAC_WATT_POWER_HIST
WHERE Alias IN
(
	SELECT Alias FROM CEVAC_WATT_POWER_XREF
	WHERE (Type = 'Emergency')
) GROUP BY UTCDateTime
