IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_SUMS_DAY'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_POWER_SUMS_DAY
END
GO

CREATE VIEW CEVAC_WATT_POWER_SUMS_DAY AS

SELECT UTCDateTime,  SUM(ActualValue) AS Total_Usage, DATEPART(year, UTCDateTime) AS Year, DATEPART(month, UTCDateTime) AS Month, DATEPART(day, UTCDateTime) AS DAY
FROM
(SELECT * FROM CEVAC_WATT_POWER_DAY
 WHERE Alias LIKE 'Building%') AS building_sums
--WHERE UTCDateTime <= GETUTCDATE() AND UTCDateTime >= DATEADD(day, -1, GETUTCDATE())
GROUP BY UTCDateTime

