IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_EMERGENCY_DAY'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_POWER_EMERGENCY_DAY
END
GO

CREATE VIEW CEVAC_WATT_POWER_EMERGENCY_DAY
AS


SELECT 'Building Emergency' AS Alias, UTCDateTime, SUM(ActualValue) AS ActualValue, DATEPART(year, UTCDateTime) AS Year, DATEPART(month, UTCDateTime) AS Month, DATEPART(day, UTCDateTime) AS Day
FROM CEVAC_WATT_POWER_RAW_DAY
WHERE Alias IN
(
	SELECT Alias FROM CEVAC_WATT_POWER_XREF
	WHERE (Type = 'Emergency')
) GROUP BY UTCDateTime
