IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_SUMS_HIST_VIEW'
AND TABLE_TYPE ='VIEW')
BEGIN
DROP VIEW CEVAC_WATT_POWER_SUMS_HIST_VIEW
END
GO

CREATE VIEW CEVAC_WATT_POWER_SUMS_HIST_VIEW AS

WITH original AS (
	SELECT UTCDateTime, dbo.ConvertUTCToLocal(UTCDateTime) AS ETDateTime, SUM(ActualValue) AS Total_Usage
	FROM
	(SELECT * FROM CEVAC_WATT_POWER_HIST
	 WHERE Alias LIKE 'Building%') AS Building
	GROUP BY UTCDateTime
)
SELECT *, DATEPART(year, ETDateTime) AS Year, DATEPART(month, ETDateTime) AS Month, DATEPART(day, ETDateTime) AS Day
FROM original