IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_SUMS_HIST_VIEW'
AND TABLE_TYPE ='VIEW')
BEGIN
DROP VIEW CEVAC_WATT_POWER_SUMS_HIST_VIEW
END
GO

CREATE VIEW CEVAC_WATT_POWER_SUMS_HIST_VIEW AS

SELECT UTCDateTime,  SUM(ActualValue) AS Total_Usage, DATEPART(year, UTCDateTime) AS Year, DATEPART(month, UTCDateTime) AS Month, DATEPART(day, UTCDateTime) AS Day
FROM
(SELECT * FROM CEVAC_WATT_POWER_HIST_VIEW
 WHERE Alias LIKE 'Building%') AS Building
GROUP BY UTCDateTime
