IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_WAP_HIST_VIEW'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_WAP_HIST_VIEW
END
GO
CREATE VIEW CEVAC_WATT_WAP_HIST_VIEW AS

WITH original AS (
	SELECT time, xref.Alias AS Alias, ssid, total_duration, predicted_occupancy, unique_users
	FROM CEVAC_WATT_WAP_HIST_RAW as raw
	INNER JOIN CEVAC_WATT_WAP_XREF as xref ON xref.WAP_Name = raw.name
	UNION
	SELECT * FROM CEVAC_WATT_WAP_EDUROAM_HIST
	UNION
	SELECT * FROM CEVAC_WATT_WAP_MORRISON_HIST
	UNION
	SELECT * FROM CEVAC_WATT_WAP_CLEMSONGUEST_HIST
	UNION
	SELECT * FROM CEVAC_WATT_WAP_RESMEDIANET_HIST
	UNION
	SELECT * FROM CEVAC_WATT_WAP_VISITORS_HIST
) SELECT *, dbo.ConvertUTCToLocal(time) AS ETDateTime FROM original