IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_WAP_HIST'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_WAP_HIST
END
GO
CREATE VIEW CEVAC_WATT_WAP_HIST AS

SELECT * FROM CEVAC_WATT_WAP_HIST_VIEW 