IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_1ST_FLOOR_HIST'
AND TABLE_TYPE ='VIEW')
BEGIN DROP VIEW CEVAC_WATT_POWER_1ST_FLOOR_HIST END
GO

CREATE VIEW CEVAC_WATT_POWER_1ST_FLOOR_HIST
AS

WITH original AS (
	SELECT '1st Floor Total' AS Alias, UTCDateTime, dbo.ConvertUTCToLocal(UTCDateTime) AS ETDateTime, SUM(ActualValue) AS ActualValue
	FROM CEVAC_WATT_POWER_RAW_HIST
	WHERE Alias IN
	(
		SELECT Alias FROM CEVAC_WATT_POWER_XREF
		WHERE (Floor = '1st Floor')
	) GROUP BY UTCDateTime
)
SELECT *, DATEPART(year, ETDateTime) AS Year, DATEPART(month, ETDateTime) AS Month, DATEPART(day, ETDateTime) AS Day
FROM original