IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_ACTIVITY') DROP PROCEDURE CEVAC_ACTIVITY;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_ACTIVITY
	@TableName NVARCHAR(MAX),
	@ProcessName NVARCHAR(MAX)
AS

INSERT INTO CEVAC_ACTIVITY_LOG(TableName, UTCDateTime, ProcessName)
VALUES (
	@TableName,
	GETUTCDATE(),
	@ProcessName
);