IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_CACHE_METRIC') DROP PROCEDURE CEVAC_CACHE_METRIC;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_CACHE_METRIC
	@Metrics NVARCHAR(500)
AS

DECLARE @tables_APPEND NVARCHAR(500);
DECLARE @Metric_name NVARCHAR(50);
DECLARE @i INT;
SET @tables_APPEND = '';
SET @i = 20;
IF OBJECT_ID('dbo.#cevac_params', 'U') IS NOT NULL DROP TABLE #cevac_params;
SELECT * INTO #cevac_params FROM ListTable(@Metrics);


WHILE (EXISTS(SELECT 1 FROM #cevac_params) AND @i > 0) BEGIN
	SET @i = @i - 1;
	SET @Metric_name = (SELECT TOP 1 * FROM #cevac_params);
	DELETE TOP(1) FROM #cevac_params;





END
DECLARE @CEVAC_CACHE_APPEND NVARCHAR(500);
SET @CEVAC_CACHE_APPEND = 'EXEC CEVAC_CACHE_APPEND @tables = ''' + @tables_APPEND + '''';
SELECT @CEVAC_CACHE_APPEND;
EXEC(@CEVAC_CACHE_APPEND)