IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_ACKNOWLEDGE_EVENT') DROP PROCEDURE CEVAC_ACKNOWLEDGE_EVENT;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_ACKNOWLEDGE_EVENT
@EventID INT,
@ACK BIT
AS

UPDATE CEVAC_ALL_ALERTS_HIST_RAW
SET Acknowledged = @ACK
WHERE EventID = @EventID;
EXEC CEVAC_CACHE_INIT @tables = 'CEVAC_ALL_ALERTS_EVENTS_HIST_VIEW';