IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CREATE_CEVAC_WATT_POWER_SUMS_HIST_VIEW') DROP PROCEDURE CREATE_CEVAC_WATT_POWER_SUMS_HIST_VIEW;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CREATE_CEVAC_WATT_POWER_SUMS_HIST_VIEW
	@output NVARCHAR(MAX) OUTPUT
AS
DECLARE @HIST NVARCHAR(100);
DECLARE @HIST_VIEW NVARCHAR(105);
DECLARE @BuildingSName NVARCHAR(100);
DECLARE @Metric NVARCHAR(100);
DECLARE @CREATEName NVARCHAR(200);

SET @BuildingSName = 'WATT';
SET @Metric = 'POWER_SUMS';
SET @HIST = 'CEVAC_' + @BuildingSName + '_' + @Metric + '_HIST';
SET @HIST_VIEW = @HIST + '_VIEW';
SET @CREATEName = 'CREATE_' + @HIST_VIEW;

DECLARE @DROP_HIST NVARCHAR(300);
SET @DROP_HIST = 'IF OBJECT_ID(' + @HIST + ') IS NULL DROP VIEW ' + @HIST;
EXEC @DROP_HIST;
DELETE FROM CEVAC_TABLES WHERE BuildingSName = @BuildingSName AND Metric = @Metric AND (Age != 'XREF' AND Age != 'PXREF');
INSERT INTO CEVAC_TABLES (BuildingSName, Metric, Age, TableName, DateTimeName, AliasName)
VALUES(
	@BuildingSName,
	@Metric,
	'HIST',
	@HIST,
	'UTCDateTime',
	'Total_Usage'
)

SET @output = '
CREATE VIEW CEVAC_WATT_POWER_SUMS_HIST_VIEW AS

WITH all_utc AS (
	SELECT UTCDateTime, COUNT(UTCDateTime) AS UTCCount FROM CEVAC_WATT_POWER_HIST
	WHERE Alias LIKE ''Building%''
	GROUP BY UTCDateTime
), full_utc AS (
	SELECT UTCDateTime
	FROM all_utc
	WHERE UTCCount >= 7
), original AS (
	SELECT UTCDateTime, dbo.ConvertUTCToLocal(UTCDateTime) AS ETDateTime, SUM(ActualValue) AS Total_Usage
	FROM
	(SELECT * FROM CEVAC_WATT_POWER_HIST
	 WHERE Alias LIKE ''Building%''
	 AND UTCDateTime IN (SELECT UTCDateTime FROM full_utc)
	 ) AS Building
	GROUP BY UTCDateTime
)
SELECT *
FROM original
';