IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CREATE_CEVAC_WATT_WAP_HIST_VIEW') DROP PROCEDURE CREATE_CEVAC_WATT_WAP_HIST_VIEW;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CREATE_CEVAC_WATT_WAP_HIST_VIEW
	@output NVARCHAR(MAX) OUTPUT
AS
DELETE FROM CEVAC_TABLES WHERE TableName = 'CEVAC_WATT_WAP_HIST';
INSERT INTO CEVAC_TABLES (BuildingSName, Metric, Age, TableName, DateTimeName, AliasName)
VALUES(
	'WATT',
	'WAP',
	'HIST',
	'CEVAC_WATT_WAP_HIST',
	'time',
	'name'
)

SET @output = '
CREATE VIEW CREATE_CEVAC_WATT_WAP_HIST_VIEW AS
SELECT * FROM CEVAC_WATT_WAP_HIST_RAW
';