IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CREATE_CEVAC_ALL_ALERTS_HIST_VIEW') DROP PROCEDURE CREATE_CEVAC_ALL_ALERTS_HIST_VIEW;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CREATE_CEVAC_ALL_ALERTS_HIST_VIEW
	@output NVARCHAR(MAX) OUTPUT
AS
DELETE FROM CEVAC_TABLES WHERE TableName = 'CEVAC_ALL_ALERTS_HIST';
INSERT INTO CEVAC_TABLES (BuildingSName, Metric, Age, TableName, DateTimeName, AliasName)
VALUES(
	'ALL',
	'ALERTS',
	'HIST',
	'CEVAC_ALL_ALERTS_HIST',
	'UTCDateTime',
	'AlertID'
)

SET @output = '
CREATE VIEW CEVAC_ALL_ALERTS_HIST_VIEW AS
SELECT * FROM CEVAC_ALL_ALERTS_HIST_RAW
';