IF EXISTS(
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'dbo'
AND TABLE_NAME='CEVAC_WATT_POWER_SUMS_HIST'
AND TABLE_TYPE ='VIEW')
BEGIN
-- If the view exists, the code in this block will run.
DROP VIEW CEVAC_WATT_POWER_SUMS_HIST
END
GO

CREATE VIEW CEVAC_WATT_POWER_SUMS_HIST AS

SELECT UTCDateTime,  SUM(ActualValue) AS Total_Usage, DATEPART(year, UTCDateTime) AS Year, DATEPART(month, UTCDateTime) AS Month, DATEPART(day, UTCDateTime) AS Day
FROM
(SELECT * FROM CEVAC_WATT_POWER_HIST
 WHERE Alias LIKE 'Building%')
GROUP BY UTCDateTime
