IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_RESOLVE_EVENT') DROP PROCEDURE CEVAC_RESOLVE_EVENT;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_RESOLVE_EVENT
@EventID INT,
@RES BIT
AS
DECLARE @ProcessName NVARCHAR(MAX);
SET @ProcessName = OBJECT_NAME(@@PROCID);
EXEC CEVAC_ACTIVITY @TableName = 'CEVAC_ALL_ALERTS_EVENTS_HIST_VIEW', @ProcessName = @ProcessName;

UPDATE CEVAC_ALL_ALERTS_HIST_RAW
SET Resolved = @RES
WHERE EventID = @EventID;
EXEC CEVAC_CACHE_INIT @tables = 'CEVAC_ALL_ALERTS_EVENTS_HIST_VIEW';