IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_TABLE_SIZE') DROP PROCEDURE CEVAC_TABLE_SIZE;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_TABLE_SIZE
	@table NVARCHAR(500)
AS
SELECT SUM (row_count)
FROM sys.dm_db_partition_stats
WHERE object_id=OBJECT_ID(@table)   
