IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_LASR_INFO') DROP PROCEDURE CEVAC_LASR_INFO;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_LASR_INFO
AS

DECLARE @BuildingSName NVARCHAR(200);
DECLARE @Metric NVARCHAR(200);
DECLARE @Age NVARCHAR(200);

SET @BuildingSName = 'WATT';
SET @Metric = 'TEMP';
SET @Age = 'HIST';

SELECT TOP 1 *
FROM CEVAC_CACHE_RECORDS AS r
INNER JOIN CEVAC_TABLES AS t ON t.TableName = r.table_name
WHERE storage = 'CSV'

AND table_name LIKE '%WATT%TEMP%HIST%'
ORDER BY update_time DESC