IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_ALIAS_OR_PSID_OUTPUT') DROP PROCEDURE CEVAC_ALIAS_OR_PSID_OUTPUT;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_ALIAS_OR_PSID_OUTPUT
	@table NVARCHAR(200),
	@Alias_or_PSID_out NVARCHAR(30) OUTPUT
AS

IF EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'Alias' AND Object_ID = Object_ID(@table))
SET @Alias_or_PSID_out = 'Alias';
ELSE IF EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'PointSliceID' AND Object_ID = Object_ID(@table))
SET @Alias_or_PSID_out = 'PointSliceID';
