IF OBJECT_ID('CEVAC_HIST_LASR') IS NOT NULL DROP PROCEDURE CEVAC_HIST_LASR;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_HIST_LASR(
	@BuildingSName NVARCHAR(MAX),
	@Metric NVARCHAR(MAX))
AS
BEGIN
DECLARE @execute BIT;
SET @execute = 1;

DECLARE @HIST NVARCHAR(MAX);
DECLARE @HIST_LASR NVARCHAR(MAX);
SET @HIST = 'CEVAC_' + @BuildingSName + '_' + @Metric + '_HIST';
SET @HIST_LASR = @HIST + '_LASR';

DECLARE @ProcessName NVARCHAR(MAX);
SET @ProcessName = OBJECT_NAME(@@PROCID);
EXEC CEVAC_ACTIVITY @TableName = @HIST_LASR, @ProcessName = @ProcessName;


DECLARE @EXEC_SQL NVARCHAR(MAX);
SET @EXEC_SQL = '
EXEC CEVAC_SP_AGG_ALL @BuildingSName = ''' + @BuildingSName + ''', @Metric = ''' + @Metric + ''';
';

PRINT @EXEC_SQL;
IF @execute = 1 EXEC(@EXEC_SQL);

END