IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CEVAC_ALIAS_OR_PSID') DROP PROCEDURE CEVAC_ALIAS_OR_PSID;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CEVAC_ALIAS_OR_PSID
	@table NVARCHAR(200)
AS

DECLARE @Alias_or_PSID NVARCHAR(30);
IF EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'Alias' AND Object_ID = Object_ID(@table))
SET @Alias_or_PSID = 'Alias';
ELSE IF EXISTS(SELECT 1 FROM sys.columns WHERE Name = N'PointSliceID' AND Object_ID = Object_ID(@table))
SET @Alias_or_PSID = 'PointSliceID';

SELECT @Alias_or_PSID
