IF EXISTS(SELECT 1 FROM sys.procedures WHERE Name = 'CHECK_XREF') DROP PROCEDURE CHECK_XREF;
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON;
GO
CREATE PROCEDURE CHECK_XREF
@BuildingSName NVARCHAR(100),
@Metric NVARCHAR(200)
AS 
DECLARE @XREF NVARCHAR(400);
DECLARE @PXREF NVARCHAR(400);
SET @XREF = 'CEVAC_' + @BuildingSName + '_' + @Metric + '_XREF';
SET @PXREF = 'CEVAC_' + @BuildingSName + '_' + @Metric + '_PXREF';
IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = @XREF) SELECT 'XREF';
ELSE IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = @PXREF) SELECT 'PXREF';
ELSE SELECT NULL;